"""Final executive design-system unification layer (presentation only)."""

# Compact token-only CSS — keep under Founder Beta protobuf budget.
EXECUTIVE_DESIGN_UNIFY_CSS = (
    "body:has(.dg-executive-shell) .app-hero{display:none!important}"
    "div[class*=st-key-workspace_valuation_archetype]{margin:0 0 var(--space-sm)!important;max-width:18rem}"
    ".dg-executive-shell__brand{border-inline-start-color:var(--color-border-strong)!important}"
    ".dg-executive-shell__room{color:var(--color-text-muted)!important}"
    ".dg-executive-shell__title-row .dg-founder-badge__mark,"
    ".dg-executive-shell__title-row .dg-founder-badge__copy strong{display:none!important}"
    ".dg-executive-shell__title-row .dg-founder-badge{"
    "border-inline-start-color:var(--color-premium)!important}"
    ".dg-ui-section-header--primary .dg-ui-section-title{"
    "color:var(--color-text-primary)!important;font:var(--type-page-title)!important}"
    ".dg-ui-section-header--secondary .dg-ui-section-title{font:var(--type-section-title)!important}"
    ".dg-ui-section-header--context .dg-ui-section-title,"
    ".dg-ui-section-header--support .dg-ui-section-title{"
    "color:var(--color-text-secondary)!important;font:var(--type-card-title)!important;"
    "opacity:var(--opacity-secondary);text-transform:uppercase!important}"
    ".dg-ui-section-subtitle,.home-command-card-note,.summary-tile-note{"
    "color:var(--color-text-muted)!important;font:var(--type-supporting-metadata)!important}"
    ".st-key-dashboard_workflow{gap:var(--space-xl)!important}"
    ".dg-ui-section-header{border-bottom:var(--border-width-default) solid var(--color-border)!important;"
    "margin:var(--space-lg) 0 var(--space-sm)!important;padding:0 0 var(--space-sm)!important}"
    ".dg-ui-section-header--primary{border-bottom-color:var(--color-border-strong)!important;margin-top:0!important}"
    ".dg-ui-section-header--support{border-bottom:0!important;margin-top:var(--space-xl)!important}"
    ".home-command-card,.summary-tile,.dg-ui-card,.trade-summary-card{"
    "background:var(--color-surface-primary)!important;"
    "border:var(--border-width-default) solid var(--color-border)!important;"
    "box-shadow:var(--shadow-none)!important}"
    ".home-command-card::after,.summary-tile::after{content:none!important}"
    ".home-command-card-primary,.home-command-card-wide{"
    "border-inline-start:var(--border-width-semantic) solid var(--color-opportunity)!important}"
    ".home-command-card-risk{border-inline-start-color:var(--color-warning)!important}"
    ".home-command-card-secondary{opacity:var(--opacity-secondary)}"
    ".home-command-card-value,.summary-tile-value{font:var(--type-primary-metric)!important}"
    ".dg-notification-item.is-unread{border-inline-start-color:var(--color-action)!important}"
    ".dashboard-clear-state{"
    "border-inline-start:var(--border-width-semantic) solid var(--color-success)!important}"
    "@media (min-width:1440px){.st-key-dashboard_workflow{gap:var(--space-3xl)!important}}"
    "@media (max-width:760px){"
    "div[class*=st-key-workspace_valuation_archetype]{display:none!important}"
    ".st-key-dashboard_workflow{gap:var(--space-lg)!important}"
    ".dg-ui-section-header--primary .dg-ui-section-title{"
    "font-size:clamp(1.35rem,6vw,1.75rem)!important}}"
)
