"""Visual-weight contract for executive information compression (presentation only)."""

# Keep compact — Founder Beta protobuf budget is tight.
EXECUTIVE_INFO_COMPRESSION_CSS = (
    ".dg-info-weight-verdict{border-inline-start:var(--border-width-semantic) solid"
    " var(--color-opportunity)!important;margin:0 0 var(--space-md)!important;"
    "padding:var(--space-md)!important;background:var(--color-surface-muted)!important}"
    ".dg-info-weight-verdict .dg-info-verdict-title{color:var(--color-text-primary);"
    "font:var(--type-card-title);margin:0}"
    ".dg-info-weight-verdict .dg-info-verdict-meta{align-items:baseline;display:flex;"
    "flex-wrap:wrap;gap:var(--space-sm);justify-content:space-between;margin-top:var(--space-xs)}"
    ".dg-info-weight-primary{margin:0 0 var(--space-sm)!important;padding:0!important;"
    "border:0!important;background:transparent!important}"
    ".dg-info-weight-primary>span{color:var(--color-text-muted);font-size:var(--font-size-badge);"
    "letter-spacing:var(--letter-spacing-badge);text-transform:uppercase}"
    ".dg-info-weight-primary>p{color:var(--color-text-primary);font:var(--font-body);"
    "font-weight:var(--font-weight-metadata);margin:var(--space-2xs) 0 0}"
    ".dg-info-weight-support{margin:0 0 var(--space-xs)!important;opacity:var(--opacity-secondary)}"
    ".dg-info-weight-advanced,.dg-info-disclosure{margin:var(--space-sm) 0!important;"
    "border:0!important;background:transparent!important}"
    ".dg-info-disclosure>summary{cursor:pointer;color:var(--color-text-muted);"
    "font-size:var(--font-size-badge);letter-spacing:var(--letter-spacing-badge);"
    "text-transform:uppercase;min-height:var(--touch-target-min);display:flex;align-items:center}"
    ".dg-info-disclosure[open]>summary{margin-bottom:var(--space-xs)}"
    ".dg-info-disclosure>p,.dg-modal-section--collapsed .dg-modal-section-body{"
    "color:var(--color-text-secondary);font:var(--font-body);margin:0}"
    ".player-dossier-recommendation-context{border-inline-start:var(--border-width-semantic)"
    " solid var(--color-opportunity)!important}"
    ".player-dossier-snapshot,.player-dossier-season-summary{border:0!important;"
    "border-top:var(--border-width-default) solid var(--color-border)!important;"
    "background:transparent!important;padding-inline:0!important}"
    ".player-dossier-career,.player-dossier-executive{opacity:var(--opacity-secondary);"
    "border:0!important;border-top:var(--border-width-default) solid var(--color-border)!important;"
    "background:transparent!important}"
    ".player-dossier-season-summary-grid{display:grid;gap:var(--space-sm);"
    "grid-template-columns:repeat(auto-fit,minmax(5.5rem,1fr));margin:var(--space-sm) 0}"
    ".player-dossier-season-summary-metric{display:grid;gap:var(--space-2xs);min-width:0}"
    ".player-dossier-season-summary-metric>span{color:var(--color-text-muted);"
    "font-size:var(--font-size-badge);letter-spacing:var(--letter-spacing-badge);"
    "text-transform:uppercase}"
    ".player-dossier-season-summary-metric>strong{color:var(--color-text-primary);"
    "font:var(--type-primary-metric);font-size:var(--font-size-body);overflow-wrap:anywhere}"
    ".player-dossier-achievement-family{color:var(--color-text-muted);font-size:var(--font-size-badge);"
    "letter-spacing:var(--letter-spacing-badge);text-transform:uppercase;"
    "margin:var(--space-sm) var(--space-md) var(--space-2xs)}"
    "@media (min-width:1024px){"
    ".trade-detail-modal .trade-matchup-compact{grid-template-columns:1fr auto 1fr}"
    ".player-quick-view-shell~section.player-dossier-snapshot,"
    ".player-dossier-decision-pair{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(0,.9fr);"
    "gap:var(--space-md);align-items:start}"
    ".dg-modal-content{max-width:42rem;margin-inline:auto}"
    "}"
    "@media (max-width:430px){"
    ".player-dossier-snapshot,.player-dossier-recommendation-context,"
    ".player-dossier-season-summary,.player-dossier-career{margin:var(--space-sm) 0!important}"
    ".player-dossier-section-heading h3{font-size:var(--font-size-body)!important}"
    "}"
)
