import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';

import AnimatedCard from '../components/AnimatedCard';
import { api, type PresentationAsset, type TeamStrategy, type TradeIdea } from '../lib/api';
import { useScreenHeaderTitle } from '../lib/useScreenHeaderTitle';
import { colors, radii, spacing } from '../theme';
import type { RootStackParamList } from '../navigation/RootNavigator';

type Props = NativeStackScreenProps<RootStackParamList, 'TradeHub'>;

const STRATEGIES: Array<{ value: TeamStrategy; label: string }> = [
  { value: 'contender', label: 'Contender' },
  { value: 'fringe_contender', label: 'Fringe Contender' },
  { value: 'retool', label: 'Retool' },
  { value: 'rebuild', label: 'Rebuild' },
  { value: 'tank', label: 'Tank' },
];

const NOT_READY_MESSAGES: Record<string, string> = {
  no_sleeper_username_linked:
    "Link your Sleeper username on the web app first — Trade Hub needs to know which roster is yours.",
  sleeper_user_not_found: "Couldn't find that Sleeper account. Double-check the linked username on the web app.",
  not_a_member_of_league: "You don't appear to own a team in this league.",
  empty_roster: "This roster doesn't have any players yet.",
  no_player_data: "Player data isn't available right now.",
};

export default function TradeHubScreen({ route, navigation }: Props) {
  const { leagueId, leagueName } = route.params;
  const [strategy, setStrategy] = useState<TeamStrategy>('retool');
  const [ideas, setIdeas] = useState<TradeIdea[] | null>(null);
  const [notReadyReason, setNotReadyReason] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useScreenHeaderTitle(navigation, 'Trade Hub', leagueName);

  const load = useCallback(
    async (nextStrategy: TeamStrategy) => {
      setLoading(true);
      setError(null);
      try {
        const result = await api.getTradeHubIdeas(leagueId, nextStrategy);
        if (result.reason) {
          setNotReadyReason(result.reason);
          setIdeas(null);
        } else {
          setNotReadyReason(null);
          setIdeas(result.ideas);
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load Trade Hub ideas.');
      } finally {
        setLoading(false);
      }
    },
    [leagueId],
  );

  useEffect(() => {
    void load(strategy);
  }, [load, strategy]);

  return (
    <FlatList
      style={styles.container}
      data={loading || error || notReadyReason ? [] : ideas ?? []}
      keyExtractor={(_, index) => String(index)}
      contentContainerStyle={styles.content}
      ListHeaderComponent={
        <View>
          <Text style={styles.disclaimer}>
            Real trade ideas for {leagueName} — generated by the same trade-ideas engine and Trust
            safety checks the web app's Trade Hub uses, tuned to the strategy below.
          </Text>
          <View style={styles.strategyRow}>
            {STRATEGIES.map((option) => (
              <TouchableOpacity
                key={option.value}
                style={[styles.pill, strategy === option.value && styles.pillActive]}
                onPress={() => setStrategy(option.value)}
              >
                <Text style={[styles.pillText, strategy === option.value && styles.pillTextActive]}>
                  {option.label}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
          {loading ? <ActivityIndicator style={styles.loading} color={colors.accent} /> : null}
          {error ? <Text style={styles.error}>{error}</Text> : null}
          {notReadyReason ? (
            <Text style={styles.notReadyText}>
              {NOT_READY_MESSAGES[notReadyReason] ?? "Couldn't build Trade Hub ideas for this league."}
            </Text>
          ) : null}
        </View>
      }
      renderItem={({ item }) => <TradeIdeaCard idea={item} />}
      ListEmptyComponent={
        !loading && !error && !notReadyReason ? (
          <Text style={styles.empty}>
            No trade idea clears the bar for this strategy right now — check back after rosters move.
          </Text>
        ) : null
      }
    />
  );
}

function AssetChip({ asset }: { asset: PresentationAsset }) {
  const label =
    asset.asset_type === 'pick'
      ? asset.label || `${asset.season ?? ''} Pick`.trim()
      : asset.name ?? 'Unknown';
  const meta =
    asset.asset_type === 'pick'
      ? asset.projected_range || 'Draft pick'
      : [asset.position, asset.team].filter(Boolean).join(' · ');
  return (
    <View style={styles.assetChip}>
      <Text style={styles.assetChipName} numberOfLines={1}>
        {label}
      </Text>
      {meta ? (
        <Text style={styles.assetChipMeta} numberOfLines={1}>
          {meta}
        </Text>
      ) : null}
    </View>
  );
}

function TradeIdeaCard({ idea }: { idea: TradeIdea }) {
  const gainColor = idea.trade_gain > 0 ? colors.success : idea.trade_gain < 0 ? colors.danger : colors.textSecondary;
  return (
    <AnimatedCard style={styles.card}>
      <View style={styles.cardHeaderRow}>
        <Text style={styles.partnerName}>{idea.partner_team_name}</Text>
        <Text style={[styles.gainLabel, { color: gainColor }]}>
          {idea.trade_gain > 0 ? '+' : ''}
          {idea.trade_gain}
        </Text>
      </View>
      <Text style={styles.rationale}>{idea.rationale}</Text>

      <View style={styles.packageRow}>
        <View style={styles.packageSide}>
          <Text style={styles.packageLabel}>You Send</Text>
          {idea.package.send.map((asset, index) => (
            <AssetChip key={`send-${index}`} asset={asset} />
          ))}
        </View>
        <View style={styles.packageSide}>
          <Text style={styles.packageLabel}>You Receive</Text>
          {idea.package.receive.map((asset, index) => (
            <AssetChip key={`receive-${index}`} asset={asset} />
          ))}
        </View>
      </View>

      <View style={styles.footerRow}>
        <Text style={styles.footerText}>{idea.confidence_label} confidence</Text>
        <Text style={styles.footerDot}>·</Text>
        <Text style={styles.footerText}>{idea.market_realism_label} realism</Text>
      </View>
    </AnimatedCard>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg, paddingBottom: spacing.xl * 4 },
  disclaimer: { fontSize: 12, color: colors.textSecondary, marginBottom: spacing.md, lineHeight: 16 },
  strategyRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginBottom: spacing.md },
  pill: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pillActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  pillText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
  pillTextActive: { color: '#fff' },
  loading: { marginVertical: spacing.xl },
  error: { color: colors.danger, textAlign: 'center', marginTop: spacing.lg },
  notReadyText: { textAlign: 'center', color: colors.textSecondary, lineHeight: 20, marginTop: spacing.xl },
  empty: { textAlign: 'center', color: colors.textSecondary, marginTop: spacing.xl, lineHeight: 20 },
  card: {
    borderLeftWidth: 4,
    borderLeftColor: colors.accent,
    padding: spacing.lg,
    marginBottom: spacing.sm,
  },
  cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xs },
  partnerName: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
  gainLabel: { fontSize: 15, fontWeight: '800' },
  rationale: { fontSize: 13, color: colors.textSecondary, lineHeight: 18, marginBottom: spacing.md },
  packageRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
  packageSide: { flex: 1 },
  packageLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: spacing.xs,
  },
  assetChip: {
    backgroundColor: colors.background,
    borderRadius: radii.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    marginBottom: spacing.xs,
  },
  assetChipName: { fontSize: 13, fontWeight: '600', color: colors.textPrimary },
  assetChipMeta: { fontSize: 11, color: colors.textSecondary, marginTop: 1 },
  footerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingTop: spacing.xs, borderTopWidth: 1, borderTopColor: colors.border },
  footerText: { fontSize: 11, color: colors.textSecondary },
  footerDot: { fontSize: 11, color: colors.textSecondary },
});
